### ISSUE TITLE
Would you mind to commit a readme?

### ISSUE THREAD

**Issue by skx300** [rootlu/MMDNE#1]
Dear Lu,

Thank you for your good work on temporal network. I am wondering would you mind to give a brief readme file describing how to import data, run the program and show the metrics?

Thank you in advance.

**Comment by rootlu** [comment]
Hi, Yang, 

Thanks for your interest in our work.

I have updated the README file and provided detailed descriptions of our code.

**Comment by skx300** [comment]
Thank you!
